-- Criação das primeiras tabelas do BD

USE trocaverde;

CREATE TABLE login(
ID INTEGER NOT NULL AUTO_INCREMENT,
email VARCHAR(70) UNIQUE NOT NULL,
senha VARCHAR(16) NOT NULL,
tipo_usuario TINYINT NOT NULL, -- 0=administrador, 1=pontuador, 2=loja, 3=cliente
PRIMARY KEY(ID));

CREATE TABLE cliente(
ID INTEGER NOT NULL,
nome VARCHAR(200) NOT NULL,
snome VARCHAR(50) NOT NULL,
telefone VARCHAR(11),
celular VARCHAR(11),
data_nasc DATE NOT NULL,
email VARCHAR(70) UNIQUE NOT NULL,
pontos INTEGER DEFAULT 0,
RG VARCHAR(10) NOT NULL,
rua VARCHAR(200) NOT NULL,
numero VARCHAR(6),
complemento VARCHAR(20),
bairro VARCHAR(30) NOT NULL,
cidade VARCHAR(50) NOT NULL,
estado VARCHAR(2) NOT NULL,
cep VARCHAR(10) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID) REFERENCES login(ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE loja(
ID INTEGER NOT NULL,
CNPJ VARCHAR(14) UNIQUE NOT NULL,
razao_social VARCHAR(200) NOT NULL,
nome_fantasia VARCHAR(200),
insc_estadual VARCHAR(50),
telefone VARCHAR(11),
email VARCHAR(70) UNIQUE NOT NULL,
autorizada BOOLEAN DEFAULT 0,
rua VARCHAR(200) NOT NULL,
numero VARCHAR(6),
complemento VARCHAR(20),
bairro VARCHAR(30) NOT NULL,
cidade VARCHAR(50) NOT NULL,
estado VARCHAR(2) NOT NULL,
cep VARCHAR(10) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID) REFERENCES login(ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE admin(
ID INTEGER NOT NULL,
nome VARCHAR(200) NOT NULL,
snome VARCHAR(50) NOT NULL,
telefone VARCHAR(11),
email VARCHAR(70) UNIQUE NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID) REFERENCES login(ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE pontuador(
ID INTEGER NOT NULL,
nome VARCHAR(200) NOT NULL,
snome VARCHAR(50)NOT NULL,
telefone VARCHAR(11),
email VARCHAR(70) UNIQUE NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID) REFERENCES login(ID) ON DELETE CASCADE ON UPDATE CASCADE);

-- #######################################################

CREATE TABLE ofertas(
cod INTEGER NOT NULL AUTO_INCREMENT,
ID_loja INTEGER NOT NULL,
nome_oferta VARCHAR(200) NOT NULL,
qtde_max INTEGER NOT NULL,
qtde_vendida INTEGER NOT NULL,
pontos INTEGER NOT NULL,
data_ativacao DATE NOT NULL,
data_validade DATE NOT NULL,
imagem VARCHAR(200),
descricao VARCHAR(200),
info VARCHAR(200),
autorizada BOOLEAN DEFAULT 0,
PRIMARY KEY(cod),
FOREIGN KEY(ID_loja) REFERENCES loja(ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE pedidos(
cod_pedido INTEGER NOT NULL AUTO_INCREMENT,
cod_oferta INTEGER NOT NULL,
cod_cliente INTEGER NOT NULL,
qtde_comprada INTEGER NOT NULL,
total_pontos INTEGER NOT NULL,   -- qtde_comprada * pts_necessarios
data_pedido DATE NOT NULL,
PRIMARY KEY(cod_pedido),
FOREIGN KEY(cod_oferta) REFERENCES ofertas(cod) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(cod_cliente) REFERENCES login(ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE reciclaveis(
cod INTEGER NOT NULL AUTO_INCREMENT,
nome VARCHAR(50),
descricao VARCHAR(200),
pontos_per_kg INTEGER NOT NULL,
PRIMARY KEY(cod));